-- Runtime metrics + Pareto scoring view generated by scripts/refresh_ledger.py
-- Seed runtime metrics from ledger/cliproxyapi_runtime_metrics_snapshot.csv as needed.

DROP TABLE IF EXISTS cliproxyapi_runtime_metrics_snapshot;
CREATE TABLE cliproxyapi_runtime_metrics_snapshot (
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  latency_ms NUMERIC,
  quality_score NUMERIC,
  source_path TEXT,
  PRIMARY KEY (provider, model)
);

DROP VIEW IF EXISTS unified_model_provider_pareto_view;
CREATE VIEW unified_model_provider_pareto_view AS
SELECT
  l.ledger_row_id,
  COALESCE(NULLIF(l.pricing_provider, ''), l.inferred_provider) AS provider,
  COALESCE(NULLIF(l.pricing_model, ''), l.canonical_model_guess) AS model,
  l.pricing_input_usd_per_mtok,
  l.pricing_output_usd_per_mtok,
  m.latency_ms AS runtime_latency_ms,
  m.quality_score AS runtime_quality_score,
  CASE
    WHEN l.benchmark_prior_rows_total > 0
      THEN CAST(l.benchmark_prior_rows_non_missing AS NUMERIC) / CAST(l.benchmark_prior_rows_total AS NUMERIC)
    ELSE NULL
  END AS benchmark_quality_score,
  (
    100.0 * (
      0.50 * COALESCE(
        (
          COALESCE(m.quality_score, 0.0) +
          COALESCE(
            CASE
              WHEN l.benchmark_prior_rows_total > 0
                THEN CAST(l.benchmark_prior_rows_non_missing AS NUMERIC) / CAST(l.benchmark_prior_rows_total AS NUMERIC)
              ELSE NULL
            END,
            0.0
          )
        ) /
        CASE
          WHEN m.quality_score IS NOT NULL
               AND l.benchmark_prior_rows_total > 0 THEN 2.0
          WHEN m.quality_score IS NOT NULL
               OR l.benchmark_prior_rows_total > 0 THEN 1.0
          ELSE 1.0
        END,
        0.0
      )
      + 0.30 * (
        CASE
          WHEN COALESCE(l.pricing_input_usd_per_mtok, l.pricing_output_usd_per_mtok) IS NULL THEN 0.0
          ELSE 1.0 / (
            1.0 + (
              COALESCE(l.pricing_input_usd_per_mtok, 0.0) +
              COALESCE(l.pricing_output_usd_per_mtok, 0.0)
            ) /
            CASE
              WHEN l.pricing_input_usd_per_mtok IS NOT NULL
                   AND l.pricing_output_usd_per_mtok IS NOT NULL THEN 2.0
              ELSE 1.0
            END
          )
        END
      )
      + 0.20 * (
        CASE
          WHEN m.latency_ms IS NULL THEN 0.0
          ELSE 1.0 / (1.0 + (m.latency_ms / 1000.0))
        END
      )
    )
  ) AS pareto_score
FROM unified_model_provider_ledger l
LEFT JOIN cliproxyapi_runtime_metrics_snapshot m
  ON m.provider = COALESCE(NULLIF(l.pricing_provider, ''), l.inferred_provider)
 AND m.model = COALESCE(NULLIF(l.pricing_model, ''), l.canonical_model_guess);
