-- Deterministic unified ledger schema generated by scripts/build_unified_ledger.py
DROP TABLE IF EXISTS unified_model_provider_ledger;

CREATE TABLE unified_model_provider_ledger (
  ledger_row_id INTEGER PRIMARY KEY,
  source_model TEXT NOT NULL,
  source_model_slug TEXT NOT NULL,
  inferred_provider TEXT NOT NULL,
  provider_mapping_rule TEXT NOT NULL,
  provider_mapping_confidence INTEGER NOT NULL,
  canonical_model_guess TEXT NOT NULL,
  model_mapping_rule TEXT NOT NULL,
  model_mapping_confidence INTEGER NOT NULL,
  pricing_provider TEXT,
  pricing_model TEXT,
  pricing_subscription_usd_month NUMERIC,
  pricing_input_usd_per_mtok NUMERIC,
  pricing_output_usd_per_mtok NUMERIC,
  pricing_cache_write_usd_per_mtok NUMERIC,
  pricing_cache_read_usd_per_mtok NUMERIC,
  pricing_tool_input_usd_per_mtok NUMERIC,
  pricing_tool_output_usd_per_mtok NUMERIC,
  benchmark_input_usd_per_mtok NUMERIC,
  benchmark_output_usd_per_mtok NUMERIC,
  benchmark_rows_total INTEGER NOT NULL,
  benchmark_rows_non_missing INTEGER NOT NULL,
  benchmark_rows_missing INTEGER NOT NULL,
  benchmark_prior_rows_total INTEGER NOT NULL,
  benchmark_prior_rows_non_missing INTEGER NOT NULL,
  benchmark_prior_rows_missing INTEGER NOT NULL,
  benchmark_distinct_total INTEGER NOT NULL,
  benchmark_distinct_non_missing INTEGER NOT NULL,
  pricing_vs_benchmark_input_delta NUMERIC,
  pricing_vs_benchmark_output_delta NUMERIC
);

DROP TABLE IF EXISTS benchmark_priors_aggregation;

CREATE TABLE benchmark_priors_aggregation (
  aggregation_row_id INTEGER PRIMARY KEY,
  inferred_provider TEXT NOT NULL,
  pricing_provider TEXT NOT NULL,
  models_count INTEGER NOT NULL,
  mapped_models_count INTEGER NOT NULL,
  prior_rows_total INTEGER NOT NULL,
  prior_rows_non_missing INTEGER NOT NULL,
  prior_rows_missing INTEGER NOT NULL
);
